server {
    listen 8080;
    host localhost;
    index index.html;

    error_page 403 ./www/error_pages/403.html;
    error_page 404 ./www/error_pages/404.html;
    error_page 405 ./www/error_pages/405.html;
    error_page 413 ./www/error_pages/413.html;
    error_page 500 ./www/error_pages/500.html;

    client_max_body_size 10000000;  # 10MB

    set_timeout 5;
    # set_timeout 5;

    location / {
        root ./www;
        index index.htmll;
        allow_methods GET;

		autoindex on;
    }

    location /post_body {
        root ./www/upload/post_body;
        allow_methods POST;
        client_max_body_size 100;   # 100B
    }

	location /directory {
		root ./YoupiBanane;
		index youpi.bad_extension;
		allow_methods GET POST;
		autoindex off;
		client_max_body_size 100000000; # 100MB
		# cgi_handler .bla /home/abenzaho/Desktop/WEBSERV/testers/cgi_tester;
        cgi_handler .bla /home/yanflous/Desktop/workspace/webserv/testers/cgi_tester;
	}

    # 301 -> Moved Permanently
    location /mosi9ar_1 {
        root ./www;
        return 301 https://www.youtube.com/watch?v=a-Gp2baNaDA;
    }

    # 302 -> temporary redirect
    location /mosi9ar_2 {
        root ./www;
        return 302 https://www.youtube.com/watch?v=a-Gp2baNaDA;
    }

    location /cgi-bin {
        root ./www/cgi-bin;
        autoindex on;
        allow_methods GET POST;
        cgi_handler .py /usr/bin/python3 .php /usr/bin/php-cgi;
    }

    location /upload {
        root ./www/upload;
        autoindex on;
        allow_methods GET POST DELETE;
    }
}

server {
    listen 9090;
    host localhost;
    index index.html;
    error_page 403 ./www/error_pages/403.html;
    error_page 404 ./www/error_pages/404.html;
    error_page 405 ./www/error_pages/405.html;
    error_page 413 ./www/error_pages/413.html;
    error_page 500 ./www/error_pages/500.html;

    client_max_body_size 10000000;

    set_timeout 5;
    # set_timeout 10;

    location / {
        root ./www;
        index index.html;
        allow_methods GET;

		autoindex on;
    }

    # 301 -> Moved Permanently
    location /mosi9ar_1 {
        root ./www;
        return 301 https://www.youtube.com/watch?v=a-Gp2baNaDA;
    }

    # 302 -> temporary redirect
    location /mosi9ar_2 {
        root ./www;
        return 302 https://www.youtube.com/watch?v=a-Gp2baNaDA;
    }

    location /post_body {
        root ./www;
        allow_methods POST;
        client_max_body_size 100;
    }

	location /directory {
		root ./YoupiBanane;
		index youpi.bad_extension;
		allow_methods GET POST;
		autoindex off;
		client_max_body_size 100000000;
		# cgi_handler .bla /home/abenzaho/Desktop/WEBSERV/testers/cgi_tester;
        cgi_handler .bla /home/yanflous/Desktop/workspace/webserv/testers/cgi_tester;
	}

    location /cgi-bin {
        root ./www/cgi-bin;
        autoindex on;
        allow_methods GET POST;
        cgi_handler .py /usr/bin/python3 .php /usr/bin/php-cgi;
    }

    location /upload {
        root ./www/upload;
        autoindex on;
        allow_methods GET POST DELETE;
    }
}
