server {
    listen 8080;
    host 127.0.0.1;
    index index.html;
    error_page 403 ./www/error/403.html;
    error_page 404 ./www/error/404.html;
    error_page 405 ./www/error/405.html;
    error_page 413 ./www/error/413.html;
    error_page 500 ./www/error/500.html;
    client_max_body_size 10000000;

    set_timeout 120;

    location / {
        root ./www;
        index index.html;
        allow_methods GET POST DELETE;

		autoindex on;
    }

    location /post_body {
        root ./www;
        allow_methods POST;
        client_max_body_size 100;
    }

	location /directory {
		root ./YoupiBanane;
		index youpi.bad_extension;
		allow_methods GET POST;
		autoindex off;
		client_max_body_size 100000000;
		cgi_handler .bla /home/yanflous/Desktop/workspace/web-server/cgi_tester;
	}

    location /cgi-bin {
        root ./www/cgi-bin;
        autoindex on;
        allow_methods GET POST;
        cgi_handler .py /usr/bin/python3 .php /usr/bin/php-cgi;
    }

    location /upload {
        root ./www;
        autoindex on;
        allow_methods GET POST DELETE;
    }
}
